#!/bin/bash
# clean.sh
# Remove all files generated by fep_runner.py setup, any AMBER simulation
# outputs, and the original template files, leaving each system directory empty.
#
# Usage:
#   bash clean.sh                  # interactive (asks for confirmation)
#   bash clean.sh --dry-run        # preview what would be removed, no deletion
#   bash clean.sh --yes            # skip confirmation prompt

set -euo pipefail

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
DRY_RUN=false
AUTO_YES=false
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --yes)     AUTO_YES=true ;;
        *) echo "Unknown option: $arg"; echo "Usage: $0 [--dry-run] [--yes]"; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# Read system_name and system legs from config.yaml (plain awk — no Python)
# ---------------------------------------------------------------------------
CONFIG="$(dirname "${BASH_SOURCE[0]}")/config.yaml"
if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: config.yaml not found at $CONFIG"
    exit 1
fi

SYSTEM_NAME=$(awk -F':[[:space:]]*' '/^system_name:/{gsub(/[[:space:]]+$/, "", $2); print $2; exit}' "$CONFIG")
if [[ -z "$SYSTEM_NAME" ]]; then
    echo "ERROR: could not read system_name from $CONFIG"
    exit 1
fi

# Extract top-level keys under the 'systems:' block (exactly 2-space indent).
# read -ra works in bash 3.2+; awk output is joined on one line for word-split.
read -ra SYSTEMS <<< "$(
    awk '/^systems:/{f=1; next}
         f && /^  [A-Za-z]/{k=$1; sub(/:$/, "", k); printf "%s ", k}
         f && /^[A-Za-z]/{exit}' "$CONFIG"
)"
if [[ ${#SYSTEMS[@]} -eq 0 ]]; then
    echo "ERROR: no systems found in $CONFIG"
    exit 1
fi

# ---------------------------------------------------------------------------
# Build removal lists per system
# ---------------------------------------------------------------------------

# All named files at the system-directory level (generated + original templates)
SETUP_FILES=(
    min.in equil.in
    ti.prmtop ti.inpcrd
    FEP_MIN.cmd FEP_EQUIL.cmd
    run_local.sh
    FEP_MIN FEP_CPU_equil
    FEP_GPU1 FEP_GPU2to4 FEP_GPU5 FEP_GPU6to8 FEP_GPU9
    equil min prod
    setup.sh
)

# Simulation outputs that AMBER / cpptraj write at the system-directory level
SIM_FILES=(
    min.out min.info min.en min.rst min.log
    equil.out equil.info equil.en equil.rst equil.nc equil.log equil.rst
    run.log
)

# Glob patterns for files with variable names (SLURM job IDs, numbered restarts)
SIM_GLOBS=(
    "equil.rst7.*"   # cpptraj-numbered restart files: equil.rst7.1 … equil.rst7.N
    "mpi_*.out"      # SLURM stdout files
    "mpi_*.err"      # SLURM stderr files
)

# ---------------------------------------------------------------------------
# Preview / execute
# ---------------------------------------------------------------------------

echo "================================================================"
echo "  FEP cleanup — system: $SYSTEM_NAME"
if $DRY_RUN; then
    echo "  Mode: DRY RUN (nothing will be deleted)"
fi
echo "================================================================"
echo ""

ANYTHING_FOUND=false

for sys in "${SYSTEMS[@]}"; do
    SYS_DIR="$SYSTEM_NAME/$sys"
    if [[ ! -d "$SYS_DIR" ]]; then
        echo "  [$sys] directory not found — skipping"
        continue
    fi

    echo "  [$sys]"

    # -- replica directories (contain all generated inputs + simulation outputs)
    REPLICA_DIRS=("$SYS_DIR"/replica_*)
    if compgen -G "$SYS_DIR/replica_*" > /dev/null 2>&1; then
        for d in "${REPLICA_DIRS[@]}"; do
            echo "    DIR  $d"
            ANYTHING_FOUND=true
        done
    fi

    # -- named files at system level
    for f in "${SETUP_FILES[@]}" "${SIM_FILES[@]}"; do
        target="$SYS_DIR/$f"
        if [[ -e "$target" || -L "$target" ]]; then
            echo "    FILE $target"
            ANYTHING_FOUND=true
        fi
    done

    # -- glob patterns at system level
    for pattern in "${SIM_GLOBS[@]}"; do
        for match in "$SYS_DIR"/$pattern; do
            if [[ -e "$match" || -L "$match" ]]; then
                echo "    FILE $match"
                ANYTHING_FOUND=true
            fi
        done
    done

    echo ""
done

if ! $ANYTHING_FOUND; then
    echo "  Nothing to remove — working directory is already clean."
    exit 0
fi

# ---------------------------------------------------------------------------
# Confirm
# ---------------------------------------------------------------------------
if $DRY_RUN; then
    echo "Dry-run complete. Re-run without --dry-run to delete the above."
    exit 0
fi

if ! $AUTO_YES; then
    read -rp "Delete all of the above? [y/N] " CONFIRM
    case "$CONFIRM" in
        [yY]|[yY][eE][sS]) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

# ---------------------------------------------------------------------------
# Delete
# ---------------------------------------------------------------------------
echo ""
for sys in "${SYSTEMS[@]}"; do
    SYS_DIR="$SYSTEM_NAME/$sys"
    [[ -d "$SYS_DIR" ]] || continue

    echo "  [$sys] removing..."

    # Replica directories
    if compgen -G "$SYS_DIR/replica_*" > /dev/null 2>&1; then
        rm -rf "$SYS_DIR"/replica_*/
        echo "    removed: replica_*/"
    fi

    # Named files (including symlinks)
    for f in "${SETUP_FILES[@]}" "${SIM_FILES[@]}"; do
        target="$SYS_DIR/$f"
        if [[ -e "$target" || -L "$target" ]]; then
            rm -f "$target"
            echo "    removed: $f"
        fi
    done

    # Glob patterns
    for pattern in "${SIM_GLOBS[@]}"; do
        for match in "$SYS_DIR"/$pattern; do
            if [[ -e "$match" || -L "$match" ]]; then
                rm -f "$match"
                echo "    removed: $(basename "$match")"
            fi
        done
    done
done

echo ""
echo "Done. Run 'python fep_runner.py setup [--mode ...]' to regenerate."
