#!/bin/bash
#SBATCH --time=1-00:00:00
#SBATCH --job-name=STEPscSCHEME
#SBATCH --ntasks=8
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1

hostname
srun numactl -s

module load PrgEnv-gnu/8.5.0

source ~/.local/amber.sh

export MPICH_NO_BUFFER_ALIAS_CHECK=1
export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK

srun --cpu-bind=cores sander.MPI -O -i STEP.in -o STEP.out -p PARM -c PREV.rst7 -r STEP.rst7 -x STEP.nc -inf STEP.mdinfo
